application:
   indico:
      key: d93a3ddfda516d9e8427e6a3530f6ad2
   elasticsearch:
      host: localhost
      port: 9300
      cluster-name: mbc
      index: a_random_index
      document-type: user
      number-of-replicas: 1
      number-of-shards: 5
      cluster-sniff: false
   
